### ISSUE TITLE
Support fo Huawei Mate 20 lite (SNE-LX1) Kirin 710 and Kirin 980

### ISSUE THREAD

**Issue by phoenixstamp** [werasik2aa/Huawei-Unlock-Tool#11]
Hello i have a huawei mate 20 lite and i was just wondering if you could add support for it since i cant find anything to unlock the frp with im really stuck with it at the moment so please could you have a look into it.

Thanks, willow

**Comment by werasik2aa** [comment]
100% incompatible CPUs with PotatoNV way unlock: Kirin 710, 710A, 710F, 810, 970, 980, 985, 990 & newer.

**Comment by werasik2aa** [comment]
CHECK SOLVED N https://github.com/werasik2aa/Huawei-Unlock-Tool/issues/18

**Comment by Lgndwilloske** [comment]
hey, its me again how do i degrade the firmware? my fb is FBLOCKED and i am locked out of FRP i think its now running either EMUI12 or 10, thanks
