### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: Данный ключ отсутствует в словаре. 

### ISSUE THREAD

**Issue by hkvert** [werasik2aa/Huawei-Unlock-Tool#13]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/105732484/822f28e0-3aba-4bb9-982b-e71e6ef3e423)
************** Текст исключения **************
System.Collections.Generic.KeyNotFoundException: Данный ключ отсутствует в словаре.
   в System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   в HuaweiUnlocker.Window.UNLBTN_Click(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в HuaweiUnlocker.UI.NButton.OnMouseUp(MouseEventArgs e)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
HuaweiUnlock
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/RELEASE/HuaweiUnlock.exe
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.Management
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

**Comment by werasik2aa** [comment]
Хм сейчас, посмотрю возможно я привел не верную ссылку

**Comment by werasik2aa** [comment]
Попробуй ещё раз, я обновил ссылки

**Comment by werasik2aa** [comment]
Возможно у тебя сайта нет в списках, или произошла ошибка... Попробуй удалить файлы languages

**Comment by werasik2aa** [comment]
Сейчас глянем, почему так..
А пока попробуй через qfill
https://github.com/werasik2aa/UnlockedHuaweiBootloader
AUM-L41.ZIP

**Comment by werasik2aa** [comment]
Исправил ссылку, теперь должно работать!

**Comment by werasik2aa** [comment]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/29414ba6-29aa-4c40-8fe2-ac03deed7730)

**Comment by hkvert** [comment]
Да, теперь работает, но выдает:

```
[INFO] Trying to unlock:  AUM-L41(FULL_METHOD2)
[INFO] Trying to unlock:  Reading GPT... Please wait
[INFO] DONE 21.12.2023 19:44:11
[ERROR] Error Reading GPT! Wrong firehose or EMMC GPT on device empty! 
[ERROR] FAILED TO UNLOCK BOOTLOADER 
```

на 4пда почитал:

```
Q9. Error Reading GPT! Wrong firehose or EMMC GPT on device empty!
A9. Попробуйте драйвера старее. Попробуйте пере-зайдите в EDL. Либо загрузчик выбирается не правильно, выберите его вручную.
Если не помогает возможно на вашем устройстве нет разметки gpt.
```

Качал кучу разных драйверов, пере-заходил в edl, но не помогло. Как понимаю у меня вариант "на вашем устройстве нет разметки gpt", и вопрос, как эту разметку сделать?

**Comment by werasik2aa** [comment]
А устройство было с разметкой до этого?

**Comment by hkvert** [comment]
> А устройство было с разметкой до этого?
без понятия

**Comment by werasik2aa** [comment]
зайдите в раздел partitions, и нажмите read gpt

**Comment by hkvert** [comment]
[INFO] Checking connection... 
[INFO] Reading GPT... Please wait 
[INFO] DONE 21.12.2023 20:11:13
[ERROR] Error Reading GPT! Wrong firehose or EMMC GPT on device empty!

**Comment by werasik2aa** [comment]
я думаю, firehose в папке с программой либо отсутствует, либо я не тот положил
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/e1041c11-1084-4e12-aec7-4f98d64de988)
должно быть так

**Comment by werasik2aa** [comment]
примерно, правда у меня нет aum

**Comment by werasik2aa** [comment]
посмотрите в диспетчере задач, нет ли программ занимающие порт
emmcdl.exe
fh_loader.exe

**Comment by werasik2aa** [comment]
Если устройство изначально не грузилось или нуждается в восстановлении используйте board
https://drive.google.com/file/d/1lMvL3xUohLRENhgO5j_FvdzMRmn9jerD/edit
а потом накатите сервисную прошивку

**Comment by werasik2aa** [comment]
Если не помогает попробуйте этот загрузчик
[Snapdragon430.zip](https://github.com/werasik2aa/Huawei-Unlock-Tool/files/13744678/Snapdragon430.zip)

**Comment by werasik2aa** [comment]
Я обновил программу в V20F, в архив добавил AUM41, должно заработать

**Comment by hkvert** [comment]
> Я обновил программу V20F, в архив добавил AUM41 теперь, должно заработать, https://github.com/werasik2aa/Huawei-Unlock-Tool/releases/tag/20

[INFO] Checking connection... 
[INFO] Reading GPT... Please wait 
[INFO] DONE 21.12.2023 20:47:35
[ERROR] Error Reading GPT! Wrong firehose or EMMC GPT on device empty!

**Comment by werasik2aa** [comment]
Рекомендую выставить в программе вот так:
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/d2962c0e-ae70-4000-8287-dcaa1a64c0ec)
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/cff6db1b-710a-425c-829f-69a500e7b4b4)

**Comment by hkvert** [comment]
в программе выставлено все так же как на скринах, и все равно ошибка [ERROR] Error Reading GPT! Wrong firehose or EMMC GPT on device empty!

**Comment by werasik2aa** [comment]
Странно очень. попробуйте отключить аккумулятор, потом войти в edl

**Comment by hkvert** [comment]
Аккумулятор всегда отключаю перед тем как заходить в edl

**Comment by werasik2aa** [comment]
Попробуйте оставить графу загрузчика пустую
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/a4761599-f286-4184-a637-8c479926a329)
как здесь.

**Comment by werasik2aa** [comment]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/22176eab-f307-4f58-ad4e-86829f522692)
проверил на atu-l31

**Comment by hkvert** [comment]
> Попробуйте оставить графу загрузчика пустую ![image](https://private-user-images.githubusercontent.com/20810116/292283013-a4761599-f286-4184-a637-8c479926a329.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxODIyMDcsIm5iZiI6MTcwMzE4MTkwNywicGF0aCI6Ii8yMDgxMDExNi8yOTIyODMwMTMtYTQ3NjE1OTktZjI4Ni00MTg0LWE2MzctOGM0Nzk5MjZhMzI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE4MDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NDcxM2MzZWM2NGYxOGQ3ZGRmYmQzOWFhYjYyMTA5Mjc1Y2U3MWQwMmU4YmZhNzk3ZTI4MGQzNzdmYmRjNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Klhe9pBX7AygbtWecDBxkjyoQFdDznFxpjatAdeE5lk) как здесь. И нажмите разблокировку. Программа должна выбрать любой подходящий примерно так

[INFO] Checking connection... 
[INFO] DONE 21.12.2023 21:06:21
[INFO] HW_ID:  NaN
[INFO] SW_ID:  NaN
[INFO] OEM_PK_HASH:  NaN
[INFO] SBL_VER:  NaN
[INFO] CPU:  ERROR: FAILED UNKNOWN ERROR
[INFO] Device cannot be readed! Please reconnect it!

**Comment by werasik2aa** [comment]
у тебя устройство видно, не читается, 
должно быть так
[INFO] HW_ID:  0x000560e1
[INFO] SW_ID:  NaN
[INFO] OEM_PK_HASH:  0x6bc369511da9cadb3a7af61574f89db385003d6241bdd1ff573dba61bf6ae119
[INFO] SBL_VER:  0x00000000
[INFO] CPU:  MSM8917 
примерно

**Comment by werasik2aa** [comment]
[INFO] Checking connection... 
[INFO] DONE 22.12.2023 1:08:44
[INFO] HW_ID:  0x000560e1
[INFO] SW_ID:  NaN
[INFO] OEM_PK_HASH:  0x6bc369511da9cadb3a7af61574f89db385003d6241bdd1ff573dba61bf6ae119
[INFO] SBL_VER:  0x00000000
[INFO] CPU:  MSM8917
[INFO] Started unlock process 
[INFO] Connected PORT:  Qualcomm HS-USB QDLoader 9008 (COM25)
[INFO] Flashing Loader:  qc_boot\AGS\Qualcomm Snapdragon 425.mbn
[INFO] DONE 22.12.2023 1:08:47
[INFO] Trying to unlock:  ATU-L31-L21-LOWER(FULL)
[INFO] Please wait:  99%
[INFO] DONE 22.12.2023 1:08:48
[INFO] Trying to Write:  aboot
[INFO] Please wait:  75%
[INFO] DONE 22.12.2023 1:08:50
[INFO] Trying to Write:  kernel
[INFO] DONE 22.12.2023 1:09:48
...
Лог успешной разблокировки должен быть примерно таков

**Comment by werasik2aa** [comment]
для проверки подключения устройства нажмите.
Оно должно предложить подходящие загрузчики
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/b4b5198a-52ac-4cae-86e5-1a1ead97d02a)

**Comment by hkvert** [comment]
отключил подпись драйверов, пере-воткнул в другой порт:
```
[INFO] HW_ID:  NaN
[INFO] SW_ID:  NaN
[INFO] OEM_PK_HASH:  NaN
[INFO] SBL_VER:  NaN
[INFO] CPU:  ERROR: FAILED UNKNOWN ERROR
[INFO] Trying to guess firehose for this device... 
[INFO] Device cannot be readed! Please reconnect it! 
```
 visual c++ redist стоят 
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/105732484/0455e243-ea79-4608-be57-6662419bca25)

**Comment by werasik2aa** [comment]
в диспетчере устройств восклицательный знак горит?

**Comment by hkvert** [comment]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/105732484/fd26c05a-e31a-4f13-9510-0f8bc0ddd441)

**Comment by werasik2aa** [comment]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/6d470611-db3e-41e6-a106-201b1cf31de1)
странно очень почему не читается

**Comment by werasik2aa** [comment]
зайди в диспетчер задач, взгляни нет ли там emmcdl или fh_Loader.exe

**Comment by hkvert** [comment]
нету

**Comment by werasik2aa** [comment]
вот это уже странно. Обычно emmcdl читает любой 
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/76857ba8-712a-4d66-b574-9e9de1aefc7e)
Попробуй через qfill прошить...
Там есть менеджер разделов

**Comment by hkvert** [comment]
```
Version 2.16
PblHack: Error - 4
Did not receive Sahara hello packet from device
Status: 6 The handle is invalid.
```

**Comment by werasik2aa** [comment]
https://4pda.to/forum/index.php?showtopic=753902&view=findpost&p=127020635
тут есть драйвер,

**Comment by hkvert** [comment]
Винда 10 с сайта майкрософт, сейчас попробую

**Comment by werasik2aa** [comment]
Если с сайта майки, то скорее всего драйвер.

**Comment by werasik2aa** [comment]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/8414a1c8-4f17-48c0-8997-78dddd2177e6)
а ещё может быть такое на ноутбуках

**Comment by werasik2aa** [comment]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/a2dbbe9c-7dd1-4dc7-8b8d-b32ae1ed8433)
А ещё у меня время близится к глубокой ночи, получится завтра продолжить работу над проблемой?
Или срочное дело?

**Comment by hkvert** [comment]
поставил тот драйвер, перезагрузил пк.  тел перевел в edl 
```
C:\RELEASE\Tools>emmcdl -p COM4 -info
Version 2.16
PblHack: Error - 4
Did not receive Sahara hello packet from device
Status: 6 The handle is invalid.
```

**Comment by hkvert** [comment]
> ![image](https://private-user-images.githubusercontent.com/20810116/292288601-a2dbbe9c-7dd1-4dc7-8b8d-b32ae1ed8433.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxODM5MDksIm5iZiI6MTcwMzE4MzYwOSwicGF0aCI6Ii8yMDgxMDExNi8yOTIyODg2MDEtYTJkYmJlOWMtN2RkMS00ZGM3LThiOGQtYjMyYWUxZWQ4NDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE4MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0N2Y0OGRiZGQ1ZTE5ZjgyYWQ3Yjk4ZjMwZTdhODY2ZTk5Zjg3MTBjMjA1NDNjZjMwODllMTdlNjZhZDViNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VlGT0HFjyqLXYV5c11GQhVky75DORcxKJQUOtayHV-Q) А ещё у меня время близится к глубокой ночи, получится завтра продолжить работу над проблемой? Или это срочное дело?

а, давайте тогда завтра продолжим

**Comment by werasik2aa** [comment]
Ну я ещё могу 30 мин уделить

**Comment by werasik2aa** [comment]
>  пк. тел перевел в edl

попробуй это

> ![image](https://private-user-images.githubusercontent.com/20810116/292287396-8414a1c8-4f17-48c0-8997-78dddd2177e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxODM2NzIsIm5iZiI6MTcwMzE4MzM3MiwicGF0aCI6Ii8yMDgxMDExNi8yOTIyODczOTYtODQxNGExYzgtNGYxNy00OGMwLTg5OTctNzhkZGRkMjE3N2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE4MjkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NjNhNDMzODE4MjliYzUyOTE5YzVlYjJkODEzYWIxZmQzNTkyMGI5MzdmMzRmZWVlYTgzNjg5YWVlNWQ5Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CUZdc-qMMv4CjPTPh40nGKd1BKGm0VaRN1QFjF0gQ38) а ещё может быть такое на ноутбуках, Нужно отключать

**Comment by hkvert** [comment]
>  а ещё может быть такое на ноутбуках, Нужно отключать

у меня компьютер, но это на всякий выключил, и все равно выдало ту ошибку

**Comment by werasik2aa** [comment]
Тогда, куда более странно. Устройство может заходить в рекавери?

**Comment by werasik2aa** [comment]
Попробуй запустить от имени администратора, некоторым помогает...

**Comment by hkvert** [comment]
> Тогда, куда более странно. Устройство может заходить в рекавери? Или только входит в dload 9008?

и в рекавери и в фастбут спокойно заходит

**Comment by hkvert** [comment]
иногда кстати устройство заходит в странный режим и показывает 3 порта 
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/105732484/1495f40b-4da7-4032-9a56-327df3236576)

**Comment by werasik2aa** [comment]
Вот это куда странно. Программа не может соеденится с устройством.
А ошибка вообще на стадии pbl hack...

Попробуйте использовать не usb3.0 а usb2.0. или наоборот. Т.к эта ошибка как я знаю выходит по трем причинам
1. Драйвера
2. Порт занят
3. Не правильное соединение testpoint.а

**Comment by werasik2aa** [comment]
https://disk.yandex.ru/d/rQ4e72f1FhbuWg/TESTPOINTS
Посмотрите тестпоинт

**Comment by werasik2aa** [comment]
Ладно, у меня время закончилось, а то спички в глаза буду вставлять. Завтра попытаем счастье заставить ваше устройство прошиваться.

А ещё попробуйте сменить кабель...

**Comment by werasik2aa** [comment]
> иногда кстати устройство заходит в странный режим и показывает 3 порта ![image](https://private-user-images.githubusercontent.com/105732484/292291016-1495f40b-4da7-4032-9a56-327df3236576.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxODUxMDEsIm5iZiI6MTcwMzE4NDgwMSwicGF0aCI6Ii8xMDU3MzI0ODQvMjkyMjkxMDE2LTE0OTVmNDBiLTRkYTctNDAzMi05YTU2LTMyN2RmMzIzNjU3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQxODUzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjU0MjE4YjAyZmY1MGU0NTZkNDk2OWVhYTNlZjQ4NWY4MTJkMWJkNTY3OWI3ZTAwMDJiMGY0NzFjMTRkNzBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ls-dRHncylkq_8bTgrxL70jlANf5a_-bexEVSAKnW9Y)

Этот режим называется manufacture. Для чтения кода донгд коробкой.

**Comment by werasik2aa** [comment]
Если необходимо можете попросить https://4pda.to/forum/index.php?showuser=6811229 помочь.
Или
https://4pda.to/forum/index.php?showuser=2988300 (в профиле телеграм)

**Comment by werasik2aa** [comment]
Вновь приветствую тебя...

**Comment by hkvert** [comment]
> Вновь приветствую тебя...

👋

**Comment by werasik2aa** [comment]
Получилось что-то?

**Comment by hkvert** [comment]
> Получилось что-то? Пока меня не было? Или не пытался :D
Не не пытался. Домой только час назад пришел.

**Comment by werasik2aa** [comment]
хм, будем пробовать?

**Comment by hkvert** [comment]
да, давайте

**Comment by werasik2aa** [comment]
Попробуйте для начало заново повторить все действия. Может сейчас сработает

**Comment by hkvert** [comment]
пере-пробовал разные дрова, порты, провода, и все также 
`Version 2.16
PblHack: Error - 4
Did not receive Sahara hello packet from device
Status: 6 The handle is invalid.`

**Comment by werasik2aa** [comment]
Хм, попробуй через qfill

**Comment by hkvert** [comment]
> Хм, попробуй через qfill



> Если устройство изначально не грузилось или нуждается в восстановлении используйте board https://drive.google.com/file/d/1lMvL3xUohLRENhgO5j_FvdzMRmn9jerD/edit а потом накатите сервисную прошивку. Лучше прошить через qfill
> 
> Если устройство работает у вас в fastboot. Просто скачайте с репозитория https://github.com/werasik2aa/UnlockedHuaweiBootloader Aum-l41.zip и прошейте через qfill используя программер с board или из папки с программы. prog_emmc_firehose.mbn или (~\HuaweiUnlock\qc_boot\устройство\Qualcomm MSM###.mbn)

?

**Comment by werasik2aa** [comment]
Попробуйте через qfill прошить те файлы, что сейчас в папке с программой

**Comment by hkvert** [comment]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/105732484/70887fa7-4a14-4342-b8ee-17fdbc9a992b)
правильно ведь все указано?

**Comment by hkvert** [comment]
```
2023-12-22 18:03:53.039    Start Download
2023-12-22 18:03:53.040    Program Path:C:\Users\zxcvbnm\Downloads\RELEASE_21.12.2023\qc_boot\AUM41\Qualcomm Snapdragon 430.mbn
2023-12-22 18:03:53.041    ***** Working Folder:C:\Users\zxcvbnm\AppData\Roaming\Qualcomm\QFIL\COMPORT_3
2023-12-22 18:05:23.064    Binary build date: Jun 25 2019 @ 03:16:15
2023-12-22 18:05:23.066    QSAHARASERVER CALLED LIKE THIS: 'C:\Users\zxcvbnm\Downloads\Qualcomm_Flash_Image_Loader_v2.0.3.5\QSaharaServer.ex'Current working dir: C:\Users\zxcvbnm\AppData\Roaming\Qualcomm\QFIL\COMPORT_3
2023-12-22 18:05:23.067    Sahara mappings:
2023-12-22 18:05:23.068    2: amss.mbn
2023-12-22 18:05:23.069    6: apps.mbn
2023-12-22 18:05:23.070    8: dsp1.mbn
2023-12-22 18:05:23.071    10: dbl.mbn
2023-12-22 18:05:23.071    11: osbl.mbn
2023-12-22 18:05:23.072    12: dsp2.mbn
2023-12-22 18:05:23.072    16: efs1.mbn
2023-12-22 18:05:23.073    17: efs2.mbn
2023-12-22 18:05:23.073    20: efs3.mbn
2023-12-22 18:05:23.074    21: sbl1.mbn
2023-12-22 18:05:23.075    22: sbl2.mbn
2023-12-22 18:05:23.076    23: rpm.mbn
2023-12-22 18:05:23.077    25: tz.mbn
2023-12-22 18:05:23.078    28: dsp3.mbn
2023-12-22 18:05:23.079    29: acdb.mbn
2023-12-22 18:05:23.080    30: wdt.mbn
2023-12-22 18:05:23.080    31: mba.mbn
2023-12-22 18:05:23.080    13: C:\Users\zxcvbnm\Downloads\RELEASE_21.12.2023\qc_boot\AUM41\Qualcomm Snapdragon 430.mbn
2023-12-22 18:05:23.080    
2023-12-22 18:05:23.080    18:05:23: ERROR: function: sahara_rx_data:276 Unable to read packet header. Only read 0 bytes.
2023-12-22 18:05:23.081    
2023-12-22 18:05:23.081    18:05:23: ERROR: function: sahara_main:982 Sahara protocol error
2023-12-22 18:05:23.081    
2023-12-22 18:05:23.081    18:05:23: ERROR: function: main:320 Uploading  Image using Sahara protocol failed
2023-12-22 18:05:23.082    
2023-12-22 18:05:23.082    
2023-12-22 18:05:23.082    Download Fail:Sahara Fail:QSaharaServer Fail:Process fail
2023-12-22 18:05:23.083    Finish Download

```

**Comment by werasik2aa** [comment]
Rawprogram0 можно не использовать... Хотя и тут ошибка

**Comment by werasik2aa** [comment]
Впервые сталкиваюсь с таким

**Comment by hkvert** [comment]
> Судя по всему нужно попробовать о катить версию прошивк.

gjghj,e.

**Comment by werasik2aa** [comment]
Попробуй ещё так тест поинт войти
https://4pda.to/forum/index.php?showtopic=908254&st=1200#entry82991648
И да бывает прога подвисает, меняем скорость порта на 115200, соответственно переподключаtмся

**Comment by werasik2aa** [comment]
Поставь скорость порта на 115200
И попробуй Хуавей тулом

**Comment by hkvert** [comment]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/105732484/4bc134c4-5f1d-4e09-b066-dff2500afb21)

**Comment by hkvert** [comment]
> Попробуй ещё так тест поинт войти И да бывает прога подвисает, меняем скорость порта на 115200, соответственно переподключаемся это с https://4pda.to/forum/index.php?showtopic=908254&st=1200#entry82991648

через точки на плате? так я так и захожу

**Comment by werasik2aa** [comment]
попробуй тут 
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/bb8d629b-d2ae-497b-91c0-331ba3b6e15a)

**Comment by werasik2aa** [comment]
а на твоём устройстве рут возможен без разблокировки?

**Comment by werasik2aa** [comment]
но почему устройство не хочет принимать команды с пк...

**Comment by werasik2aa** [comment]
[quectel-qdloader-9008-1424763.zip](https://github.com/werasik2aa/Huawei-Unlock-Tool/files/13754387/quectel-qdloader-9008-1424763.zip)
есть ещё такой драйвер

**Comment by werasik2aa** [comment]
[quectel-qdloader-9008-1424763.zip](https://github.com/werasik2aa/Huawei-Unlock-Tool/files/13754393/quectel-qdloader-9008-1424763.zip)
Вот такой драйвер попробуй

**Comment by werasik2aa** [comment]
У тебя часом qpst в фоне не работает?

**Comment by hkvert** [comment]
> У тебя часом qpst в фоне не работает?

неа

**Comment by werasik2aa** [comment]
Замени в папке с программой tools\emmcdl.exe, на данный. Взял с https://4pda.to/forum/index.php?showtopic=908254&st=4640#entry105557135
[emmcdl.zip](https://github.com/werasik2aa/Huawei-Unlock-Tool/files/13754457/emmcdl.zip)

**Comment by hkvert** [comment]
.\emmcdl.exe -p COM3 -info
Version 2.15
PblHack: Error - 4
Did not receive Sahara hello packet from device
Status: 6 The handle is invalid.

**Comment by werasik2aa** [comment]
попробуй от имени админа запустить командную стироку
может emmcdl не может добраться до устройства

**Comment by hkvert** [comment]
таже ошибка

**Comment by werasik2aa** [comment]
Попробуйте перезапустить компьютер в режиме отключенной проверки подписи драйверв

**Comment by werasik2aa** [comment]
Если не сработает то, можете попросить andro_81 https://4pda.to/forum/index.php?showuser=2988300 (в профиле телеграмм). Он разблокирует устройство через донгл по удаленному управлению... 
Либо этот человек. тоже может помочь бесплатно https://4pda.to/forum/index.php?showuser=6811229 так-же через донгл...

Всё что могу сказать на данный момент... 
Возможно проблема в системе, либо в устройстве. Если emmcdl.exe не читает устройство говорит о том, что проблема одна из двух.

**Comment by hkvert** [comment]
спасибо
