### ISSUE TITLE
Kirin 980

### ISSUE THREAD

**Issue by drogba72** [werasik2aa/Huawei-Unlock-Tool#15]
Hi,

I saw that Kirin 980 didn't be manage by your tool.
Do you know if a solution exist please ?

Great job and regards friend

**Comment by werasik2aa** [comment]
Exist but i don' t know where to test it...
https://github.com/werasik2aa/UnlockedHuaweiBootloader

**Comment by werasik2aa** [comment]
And i know that loaders

**Comment by werasik2aa** [comment]
You can try new 980 kirin loaders at your own risk. So i'm begging you to not test if you scared.

**Comment by werasik2aa** [comment]
You can try new 980 kirin loaders at your own risk. So i'm begging you to not test if you scared.
