### ISSUE TITLE
[Issue] TWRP recovery not responding to touch

### ISSUE THREAD

**Issue by A2B1C4** [werasik2aa/Huawei-Unlock-Tool#17]
When I click read info, I am getting this error:
[WARN] Not Found PCUI 
[WARN] Not Found DBADAPTER

**Comment by werasik2aa** [comment]
Because there's no read bootloader code functions. This function just for test. U can unlock your bootloader via 9008 mode

**Comment by werasik2aa** [comment]
Using button Download And Unlock...

**Comment by werasik2aa** [comment]
how to use (Old video)
https://www.youtube.com/watch?v=Hhmm2IOrbv4

**Comment by werasik2aa** [comment]
yes

**Comment by werasik2aa** [comment]
The first try to wipe data. If still bootlooop
 you need install .zip which decrypt the storage data,
 than you need wipe data in twrp

**Comment by A2B1C4** [comment]
[no-verity-opt-encrypt-6.1.zip](https://github.com/werasik2aa/Huawei-Unlock-Tool/files/13812860/no-verity-opt-encrypt-6.1.zip)
Do you mean flashing this .zip using fastboot?

**Comment by werasik2aa** [comment]
ys

**Comment by werasik2aa** [comment]
twrp

**Comment by A2B1C4** [comment]
I can't flash the recovery, looks like I made a mistake
![Screenshot 2024-01-02 214109](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/52495583/a953fcf6-896f-41d6-ac7d-db79f3bf8554)

**Comment by A2B1C4** [comment]
![Screenshot 2024-01-02 215037](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/52495583/19d59ba9-d05d-4bbc-ae11-63c6f44a803e)
See this one too, it might help.

**Comment by werasik2aa** [comment]
for flash twrp u need to fastboot flash recovery_ramdisk #.img

**Comment by A2B1C4** [comment]
OK, I will check the guide and I will tell you what happens after.

**Comment by A2B1C4** [comment]
Good news, I flashed the recovery, bad news, the screen is not working.

**Comment by werasik2aa** [comment]
Sorry for long answer because wes deep night. 
hmm, on my device atu-l31 it's working good.  maybe try:
1  Try to flash board firmware https://androidhost.ru/SEj
2 then flash the stock firmware via sd card/otg update
3 then try unlock device with tool. It's should help with unlocking

I know it's russian forum, but you can contact with https://4pda.to/forum/index.php?showuser=6811229 in QMS(Dm messages)
he has dongle box and can unlock your device with unlock code for free.

**Comment by A2B1C4** [comment]
No problem, my device is ATU-L31, but it is international version, I flashed the recovery, the problem is that when TWRP recovery boots, the screen isn't working, I can't touch anything, I will try another TWRP recovery and tell you how it goes.

**Comment by werasik2aa** [comment]
hm . Sometimes i have this error too.
You can use adb shell twrp
commands

**Comment by A2B1C4** [comment]
Is there any non touch recovery for the ATU-L31? Because the twrp recovery is not responding to touch at all

**Comment by werasik2aa** [comment]
try to use 
adb shell twrp sideload
adb sideload #.zip
adb shell twrp wipe data

**Comment by werasik2aa** [comment]
you can controll twrp functions with adb shell
then use
twrp

**Comment by A2B1C4** [comment]
I booted to edl, but the link is dead, I cant download it from that link, I also don't have a way to install the board firmware.

**Comment by A2B1C4** [comment]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/52495583/a428e97a-2732-48f5-84b9-daea188cbab8)
I am also seeing this when I flash the recovery.

**Comment by werasik2aa** [comment]
for download the image need to login in .

**Comment by werasik2aa** [comment]
for install booard software you need
1. qfill
2. Tool for short pins on
3. And firmware

For download the images from 4pda need to log in

**Comment by A2B1C4** [comment]
I flashed one GSI rom using fastboot, and the twrp recovery magically worked, but the gsi rom is stuck on boot screen and cant conitune to system, I want to try android GSIs roms, and so far, none of them work, all of them are stuck on the boot screen.

**Comment by werasik2aa** [comment]
You need to write vendor andr9 for gsi 9

**Comment by werasik2aa** [comment]
https://drive.google.com/drive/mobile/folders/1aFTTMSArwBuF5tsJBkWJ7f_d7IQc7zyy
Vendor

And with current unlock don't try to flash a custom kernel! The kernel.img patched for avoid bootloop on gsi's rom.

**Comment by A2B1C4** [comment]
Should I install the kernel and vendor after flashing the gsi?

**Comment by werasik2aa** [comment]
You must install onky vendor. Don't touch kernel

**Comment by A2B1C4** [comment]
Should I flash the vendor after flashing the gsi image or before flashing the gsi image?

**Comment by werasik2aa** [comment]
You xan flash vendor after as well as you can flash it before. Just need to so e fix size of vendor in twrp if its won't be flashed

**Comment by A2B1C4** [comment]
The touch screen is not working in twrp again, so I will try to flash using fastboot and I will comment what happens next.

**Comment by A2B1C4** [comment]
I used fastboot flash vendor VENDOR.img, output is failed(remote: 'size too large')

**Comment by werasik2aa** [comment]
Hmm for workin touch in twrp try
Fastboot erase userdata
Fastboot format userdata
Fastboot -w

**Comment by A2B1C4** [comment]
I will try and I will comment any updates here.

**Comment by werasik2aa** [comment]
Ok:)

**Comment by A2B1C4** [comment]
I am getting this error when flashing vendor:
fastboot flash vendor VENDOR.img
Sending 'vendor' (507596 KB)                       OKAY [ 16.864s]
Writing 'vendor'                                   FAILED (remote: 'size too large')
fastboot: error: Command failed

**Comment by werasik2aa** [comment]
hm strange

**Comment by werasik2aa** [comment]
you need use an Hut and flash vendor throught gpt manager

**Comment by A2B1C4** [comment]
The biggest problem for me is the touch screen problem, I don't want to go back to the stock firmware, if the touch works on twrp, then I can flash the vendor image using the twrp, fixing the touch problem is the most important thing for me.

**Comment by werasik2aa** [comment]
For fix touch sometimes helps
fastboot erase userdata
fastboot erase cache
but...

**Comment by A2B1C4** [comment]
Also, is there a way to install system and vendor images using the adb shell commands?

**Comment by werasik2aa** [comment]
hmm only .zip 
adb shell twrp sideload
adb sideload somesystemrom.zip

**Comment by A2B1C4** [comment]
Is there any other custom recovery for the ATU-L31 that is not-touch recovery?

**Comment by werasik2aa** [comment]
Nah exist 2 types on 4pda

**Comment by werasik2aa** [comment]
[twrp_3.3.1_atomu_20190824.zip](https://github.com/werasik2aa/Huawei-Unlock-Tool/files/13844819/twrp_3.3.1_atomu_20190824.zip)
Try this

**Comment by A2B1C4** [comment]
OK, I will sideload it

**Comment by A2B1C4** [comment]
Nope, not working too, the phone keeps booting back into fastboot mode, and touch not working

**Comment by werasik2aa** [comment]
Try to flash stock recovery and full ota, then try unlock again

**Comment by A2B1C4** [comment]
How?

**Comment by A2B1C4** [comment]
> Twrp is very weird, I kept holding the volume + volume - and power button, and I kept holding them until it restarted for like 5 times, and decided to boot to twrp, and it worked again, anyway, I would like to say that there is no vendor partition on the phone, at least it does not show up in the advanced wipe section

**Comment by werasik2aa** [comment]
Hm strange thing, flash the stock recovery from fastboot and write full ota.
Then try again unlock

**Comment by A2B1C4** [comment]
![IMG_20240105_220401.jpg](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/52495583/be3c347a-100b-42bf-af6a-3930914b00ce)

![2024-01-05-22-03-04-207.jpg](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/52495583/811c666b-965a-4cc2-9aa6-8c59010be5a1)

Look at these images, they might help

**Comment by A2B1C4** [comment]
Where can I find recover_ramdisk and erecovery_ramdisk? Are they in the update.app?

**Comment by werasik2aa** [comment]
Yes recovery_ramdisk and erecovery_ramdisk exist in Update.app

**Comment by A2B1C4** [comment]
I flashed both files, but I can't boot to recovery now

**Comment by werasik2aa** [comment]
why you can't boot to recovery?

**Comment by werasik2aa** [comment]
hm maybe the firmware from another atu?

**Comment by A2B1C4** [comment]
Where can I download the firmware?

**Comment by werasik2aa** [comment]
https://androidhost.ru/search.html

**Comment by werasik2aa** [comment]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/be88b942-74e5-4660-a4bc-05b9b79f695b)
write like that in search

**Comment by werasik2aa** [comment]
there's many firmwares

**Comment by A2B1C4** [comment]
I will download the firmware again, and I will comment here for updates

**Comment by A2B1C4** [comment]
I have telegram, but I don't use it much, and the pc that I am using is not mine, I will have to return it soon, so I can't do remote control

**Comment by werasik2aa** [comment]
oh, ok. So for unlock we need to flash the stock rom and after retry our way.

**Comment by A2B1C4** [comment]
I want flash board firmware using the fastboot, is that possible?

**Comment by werasik2aa** [comment]
yes,

**Comment by werasik2aa** [comment]
just use the board firmware + adb tools inside fastboot firmware and run emui### .bat file

**Comment by A2B1C4** [comment]
OK, I am flashing the files, I did run the emui bat file inside the fastboot folder, I did manage to boot

**Comment by werasik2aa** [comment]
I want apologize for my long answers. I was workin on unlocking the Kirin 710 Mate 20 lite. So now i;m free almost ;D

**Comment by werasik2aa** [comment]
Now with sd card update install the stock rom

**Comment by A2B1C4** [comment]
OK

**Comment by A2B1C4** [comment]
I put the UPDATE.APP in sd card, but it is not being detected

**Comment by werasik2aa** [comment]
you need to put update.app in dload folder

**Comment by werasik2aa** [comment]
Put UPDATE.APP IN folder dload

**Comment by A2B1C4** [comment]
OK, I am doing that right now

**Comment by werasik2aa** [comment]
https://www.youtube.com/watch?v=kPTR40h0tgw

Tutorial ;D

**Comment by werasik2aa** [comment]
you can use usb update.app installer
https://disk.yandex.ru/d/4XkfHTWbzjTaVw

**Comment by A2B1C4** [comment]
I am copying the dload folder to the sdcard, lets hope it works

**Comment by A2B1C4** [comment]
OK, update success

**Comment by werasik2aa** [comment]
so which result? downloaded another?

**Comment by A2B1C4** [comment]
Result is very good, I managed to install the stock firmware back to the phone

**Comment by werasik2aa** [comment]
good! ;D

**Comment by A2B1C4** [comment]
I will try your unlock software, but I hope that the phone doesn't get bricked this time.

**Comment by werasik2aa** [comment]
for brick phone needs to damage the chip ;D

**Comment by A2B1C4** [comment]
![2024-01-07-13-55-36-373.jpg](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/52495583/e20e9538-9510-4fe8-aa80-a132b58d9c15)

Look at this error, it shows up after clicking the detect button.

**Comment by werasik2aa** [comment]
strange, but it's detetcting your phone well, but it's useless button just for check connection

**Comment by werasik2aa** [comment]
the error can cause only language.ini files

**Comment by werasik2aa** [comment]
Try to unlock it

**Comment by A2B1C4** [comment]
I will try to unlock it again and I will give you the updates.

**Comment by A2B1C4** [comment]
OK, done, now, should I reboot to erecovery and format?

**Comment by werasik2aa** [comment]
yes

**Comment by A2B1C4** [comment]
OK, bootloop again, I am downloading the firmware using erecovery

**Comment by werasik2aa** [comment]
hmm, try to flash vendor maybe now?

**Comment by A2B1C4** [comment]
My fault is that I did not allow the bootloader to be unlocked in the settings, I will try now

**Comment by werasik2aa** [comment]
Oh, really maybe this reason

**Comment by A2B1C4** [comment]
OK, done

**Comment by A2B1C4** [comment]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/52495583/cf97231e-d111-4212-a775-4663177c4d5c)

**Comment by werasik2aa** [comment]
nah fastboot oem device-info

**Comment by werasik2aa** [comment]
if it's says about unlock try to wipe data from erecovery and boot system

**Comment by A2B1C4** [comment]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/52495583/880b3b6c-c7d6-4f83-8acc-455bdb6724b2)

**Comment by A2B1C4** [comment]
Is it OK to wipe data from fastboot too?

**Comment by werasik2aa** [comment]
first need to wipe data from recovery.in fastboot breaks data encryption

**Comment by A2B1C4** [comment]
I did, I wiped data and cache in the erecovery, but the device is still in bootloop

**Comment by werasik2aa** [comment]
bootloop in huawei logo first? or bootloop of system logo?

**Comment by A2B1C4** [comment]
No, it bootloops on the second logo

**Comment by werasik2aa** [comment]
But vendor flashed right?

**Comment by werasik2aa** [comment]
https://4pda.to/forum/index.php?showtopic=909094&st=960#entry87791760

**Comment by A2B1C4** [comment]
I am going to install twrp now

**Comment by A2B1C4** [comment]
Do I have to flash the zip of the gsi? or extract and isntall .img file

**Comment by werasik2aa** [comment]
The system its .img as system image

**Comment by werasik2aa** [comment]
Extract the .img file and flash it in twrp as system image

**Comment by A2B1C4** [comment]
Should I flash the decrypt file first before flashing gsi image?

**Comment by A2B1C4** [comment]
![2024-01-08-00-03-04-395.jpg](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/52495583/60078343-bd42-4a94-9f48-d9ecb4012872)

I also got this error when flashing vendor.img file

**Comment by werasik2aa** [comment]
Hm its means, the vendor size bigger then should be, but its strange...
We need to resize that vendor partition 
So now we fixed twrp touch working. But
Why this happened

**Comment by A2B1C4** [comment]
Yes, it is the vendor partition

**Comment by werasik2aa** [comment]
gpt partition of vendor lower size then vendor.img size it's very strange

**Comment by werasik2aa** [comment]
so we need use parted for resize it

**Comment by A2B1C4** [comment]
There is also one more thing, I can't mount the vendor partition

**Comment by werasik2aa** [comment]
hm. go to fastboot and write
fastboot format vendor

**Comment by werasik2aa** [comment]
which i modified

**Comment by werasik2aa** [comment]
Fastboot flash partition **gpt_both0.bin**
[This gpt inside.zip](https://github.com/werasik2aa/Huawei-Unlock-Tool/files/13857784/This.gpt.inside.zip)

**Comment by A2B1C4** [comment]
Can I flash the zip using twrp?

**Comment by werasik2aa** [comment]
nah, it's impossible
only from fastboot. Inside .zip it's .bin file

**Comment by A2B1C4** [comment]
OK, I will flash it in fastboot

**Comment by werasik2aa** [comment]
now 
fastboot format userdata
fastboot format vendor

**Comment by A2B1C4** [comment]
OK

**Comment by A2B1C4** [comment]
In the meantime, as soon as I rebooted from the fastboot mode back to the twrp recovery, it became unresponsive again.

**Comment by werasik2aa** [comment]
hm try to 
fastboot erase userdata
fastboot erase cache
fastboot erase persist

**Comment by werasik2aa** [comment]
Try to flash vendor.img and gsi with fastboot as i say above . I think should work

**Comment by A2B1C4** [comment]
OK

**Comment by A2B1C4** [comment]
Good, I was able to flash vendor using fastboot, can I also flash gsi using fastboot too?

**Comment by werasik2aa** [comment]
you can flash gsi too

**Comment by A2B1C4** [comment]
OK, I flashed gsi using fastboot, fastboot -w then reboot

**Comment by werasik2aa** [comment]
yes. And let it bootup

**Comment by A2B1C4** [comment]
OK, I forgot to wipe data, the system did bootloop, but it rebooted back to erecovery and managed to wipe data there, and the gsi did boot up.

**Comment by werasik2aa** [comment]
so it's working yes?

**Comment by A2B1C4** [comment]
Yes, it is working, gsi full boot.

**Comment by A2B1C4** [comment]
Model is ATU-L31

**Comment by werasik2aa** [comment]
Vendor for gsi9 : https://drive.google.com/drive/mobile/folders/1aFTTMSArwBuF5tsJBkWJ7f_d7IQc7zyy
Patched GPT if vendor size wont be flashed : [This gpt inside.zip](https://github.com/werasik2aa/Huawei-Unlock-Tool/files/13857784/This.gpt.inside.zip)
TWRP : https://4pda.to/forum/index.php?showtopic=909094&st=1000#entry88299205

**Comment by Rolan000** [comment]
У меня была такая проблема но после того как я все сделал все что было описано здесь, мой телефон доходит до загрузочного экрана и выключается а потом он запускается в ерекавери, как это проблему решить? мой телефон Honor 7c Aum-L41, прошивка pixel experience 9.0 aonly, девятый андроид .
