### ISSUE TITLE
Kirin Unlocker doesn't work

### ISSUE THREAD

**Issue by KaroloBC** [werasik2aa/Huawei-Unlock-Tool#18]
Hello, i tried to unlock bootloader on Mate 20 Lite (EMUI 10, 10.0.0.270); tool crashes (doing nothing after uploading xloader) when uploading bootloader to phone.
Log:

=============UNLOCKER BL/FRP (KIRIN TESTPOINT)============= 
[INFO] Checking connection... 
[INFO] Parsing: UnlockFiles\KIRIN710\manifest.xml 
[INFO] TITLE CPU: Kirin 710 
[INFO] DIR: KIRIN710 
[INFO] Verifying images... 
[INFO] Uploading bootloader: KIRIN710 
[INFO] -xloader

**Comment by KaroloBC** [comment]
yeah, my name on telegram is szczurek (without profile photo)

**Comment by werasik2aa** [comment]
Otherwise you can test this what where i took that loaders
[Uploading PotatoNV-Extra.zip…]()

**Comment by werasik2aa** [comment]
[Uploading PotatoNV-Extra.zip…]()
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/e97e318f-210e-4c6f-ac98-12c2d1b05170)
is that you?

**Comment by KaroloBC** [comment]
no. maybe u can send me your name? it will be faster, i guess

**Comment by werasik2aa** [comment]
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/fd0dd6c7-447e-4346-a6ed-67383889d42e)
try find

**Comment by werasik2aa** [comment]
otherwise you can test it https://raw.githubusercontent.com/werasik2aa/Huawei-Unlock-Tool/HUT/POTATONVBETA_NOTMINE.zip

**Comment by KaroloBC** [comment]
I sent DM to you on telegram.

**Comment by werasik2aa** [comment]
i think we need 100% downgrade the firmware

**Comment by KaroloBC** [comment]
yeah, but where we can get rollback package? on androidfilehost it doesnt
exist (i mean emui 9.1, because trying to downgrade directly to emui 9 ends
with software install failed, emui 9.1 downgrade only exists for singlesim
SNE-L01 or my model SNE-L21 but other regions). I will answer you on
Telegram after school.

śr., 3 sty 2024, 06:20 użytkownik Strong Recommend ***@***.***>
napisał:

**Comment by werasik2aa** [comment]
https://androidhost.ru/search.html

**Comment by werasik2aa** [comment]
Unlocked. 
![image](https://github.com/werasik2aa/Huawei-Unlock-Tool/assets/20810116/b2eaaedc-cb8a-42eb-906d-206d8af6447d)
SNE-LX1 9.0.1.164
