### ISSUE TITLE
TRT-L21A frp issue qualcomm chip

### ISSUE THREAD

**Issue by hakeem320** [werasik2aa/Huawei-Unlock-Tool#26]
[12-29-32=LOG.txt](https://github.com/user-attachments/files/16064293/12-29-32.LOG.txt)

please check issue

**Comment by werasik2aa** [comment]
Hmm looks like your device doesn't has frp partition. So only devinfo flashed.

That means universal unlock method doesn't work for you

**Comment by hakeem320** [comment]
But halabtech tool did the job by using ur firehorse

**Comment by werasik2aa** [comment]
Because they know where it stores
