### ISSUE TITLE
wdym 980 "in theory"

### ISSUE THREAD

**Issue by ArhumPyPorts** [werasik2aa/Huawei-Unlock-Tool#29]
have you tried kirin 980s? also did you find any testers? i might be able to find one for you

**Comment by werasik2aa** [comment]
androudutilitytool can
then just flash fastboot.img via fastboot to permament memory possible to unlock device half permament

**Comment by werasik2aa** [comment]
1. Watch YouTube for do the temp unlock
2. Downgrade os to lower version with it
3. Try to use first part if fastboot shows white screen, after you can flash fastboot.img to device.... For do full unlock
