### ISSUE TITLE
program dont see my phone in edl

### ISSUE THREAD

**Issue by KittenPro** [werasik2aa/Huawei-Unlock-Tool#3]
![Снимок](https://user-images.githubusercontent.com/89066248/226853672-20129443-4535-4790-8309-fe1fd48184c0.PNG)

**Comment by werasik2aa** [comment]
Are you have drivers for qualcomm?

**Comment by werasik2aa** [comment]
You need switch device in dropfoen list

**Comment by werasik2aa** [comment]
> ![Снимок](https://user-images.githubusercontent.com/89066248/226853672-20129443-4535-4790-8309-fe1fd48184c0.PNG)

So for do action always need to select device in dropdown.
