### ISSUE TITLE
[INNACTIVE] [Request] nova 5t

### ISSUE THREAD

**Issue by Ninjaa90** [werasik2aa/Huawei-Unlock-Tool#31]
does it support nova 5t?  kirin 980

**Comment by tomaszk8266** [comment]
Readme:
> May support 620|620(CAM)|65x_a|65x_b|710|810|925|935|950|955|960|970 . in theory 980!

So u can try.

**Comment by werasik2aa** [comment]
1. Temp unlock with androidutility tool.
2. Need find os which will show white screen. With unlock messages.
3. Then flash fastboot direct to memory.
