### ISSUE TITLE
with installed qualcomm drivers my device see how huawei y6 prime 2018

### ISSUE THREAD

**Issue by trippyth4mine** [werasik2aa/Huawei-Unlock-Tool#5]
i know that is not a issue of your application, but i really need help please (and i see many peoples have same problem)
i installed adb, installed qualcomm drivers, but my device always see how huawei y6 prime 2018. tried reboot to edl by using adb, install husuite, remove husuite, reinstall qualcomm drivers, but in result it doesnt work (in device manager i didnt found qualcomm label  in ports even with drivers and rebooting edl by adb)

**Comment by werasik2aa** [comment]
Open back of phone short the dots (testpoint) on board and connect device to pc .
