### ISSUE TITLE
Add Support Flash Dload

### ISSUE THREAD

**Issue by alisakkaf** [werasik2aa/Huawei-Unlock-Tool#8]
Please Add Flash UPDATE.APP in reocvery mode dload mode

**Comment by werasik2aa** [comment]
Maybe soon Will be added. But Its hard to do it.

**Comment by alisakkaf** [comment]
Nothing is impossible...you can do it sir 
god bless you

**Comment by werasik2aa** [comment]
exist only one app for do it in recovery mode

**Comment by werasik2aa** [comment]
https://disk.yandex.ru/d/rQ4e72f1FhbuWg/TRY-UNLOCK%3F/Update-DbadapterV1011

**Comment by werasik2aa** [comment]
https://disk.yandex.ru/d/rQ4e72f1FhbuWg/TRY-UNLOCK%3F/Update-DbadapterV1009

**Comment by werasik2aa** [comment]
three versions

**Comment by werasik2aa** [comment]
No answers
